<a href="https://colab.research.google.com/github/Aryan123Yad/numpy-practice/blob/main/aryan2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
import numpy as np

arr = np.array([10,20,30,40,])
print(arr)

[10 20 30 40]


In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,])

print(arr)
print("sum:",np.sum(a))
print("mean:",np.mean(a))
print("std:",np.std(a))
print("var:",np.var(a))

[10 20 30 40]
sum: 15
mean: 3.0
std: 1.4142135623730951
var: 2.0


In [ ]:
l=[[1,2,3],[4,5,6],[7, 8,9]] #this is list

l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(l)
array=[[1,2,3],
 [4,5,6],
  [7, 8,9]]

array generation function

In [ ]:
arr =np.arange(1,11,)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr =   np.zeros((4,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr =np.ones((4,4 ,))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr =np.linspace(1,5,5)
arr


array([1., 2., 3., 4., 5.])

random generation function

In [ ]:
np.random.rand(10)

array([0.5453007 , 0.59779014, 0.27371941, 0.38244318, 0.78270418,
       0.35816733, 0.50493068, 0.05630999, 0.26584607, 0.32504328])

In [ ]:
np.random.randn(10)

array([ 1.10138128, -1.82835008,  1.42270823,  2.00249256,  0.671173  ,
        0.34675436, -0.4403387 ,  1.13615649,  0.26071063,  0.34041602])

In [ ]:
np.random.randint(10,20,10)

array([11, 12, 15, 15, 19, 16, 16, 12, 17, 13])

array attribute


In [ ]:
arr =np.array([[1,2,3,],[4,5,6],[7,8,9,]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.shape

(3, 3)

In [ ]:
arr.size

9

In [ ]:
arr.dtype

dtype('int64')

array methods

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.min()


np.int64(1)

In [ ]:
arr.max()

np.int64(9)

In [ ]:
arr.sum()

np.int64(45)

In [ ]:
np.sum(arr,axis = 0)

array([12, 15, 18])

In [ ]:
arr.mean()

np.float64(5.0)

In [ ]:
arr.std()

np.float64(2.581988897471611)

In [ ]:
arr.argmax()

np.int64(8)

In [ ]:
arr.argmin()

np.int64(0)

reshaping and resizeing


In [ ]:
arr =np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [ ]:
import numpy as np

numpy indexing and slicing of vector

In [ ]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[9]

np.int64(10)

In [ ]:
arr_slice = arr[1:6]
arr_slice

array([2, 3, 4, 5, 6])

In [ ]:
arr[4]

np.int64(5)

numpy indexing and sliceing of matrix

In [ ]:
arr = np .arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr[5,4]

np.int64(30)

In [ ]:
slice =arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [ ]:
slice =arr[0:3,1:4]
slice

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])